### ISSUE TITLE
Figure out which smiles are accepted by CDK

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-msfinder#28]
We need to find a way how to get SMILES from InChI in a way that it works in msfinder
The current options are:

- Canonical smiles from pubchem
- Isomeric smiles from pubchem
- Canonical Smiles from IDSM
- Isomeric Smiles from IDSM
- SMILES computed from InChI using openbabel / chemical toolbox
- SMILES computed from InChI using matchms/rdkit chem

We need to find an example dataset where CDK fails and check with different SMILES to see which one works best.

**Comment by ElliottJP** [comment]
Typically - we were using Data Warrior - dependencies here (https://github.com/thsa/datawarrior) and then Open Babel in the group. Isomeric smiles are favourable where possible.

**Comment by hechth** [comment]
Isomeric SMILES from IDSM seem to work fine.

**Comment by zargham-ahmad** [comment]
inchi -> isomeric_smiles from pubchem also seems to work fine.
